USE nfl2015;
TRUNCATE plays;
DROP TABLE plays;
CREATE TABLE plays (Idx INT NOT NULL PRIMARY KEY,
                    Unnamed VARCHAR(5), Date DATE, 
                    GameID CHAR(10) NOT NULL,
                    Drive INT,
                    qtr INT,
                    down FLOAT(2,1),
                    time CHAR(5),
                    TimeUnder INT,
                    TimeSecs FLOAT(5,1),
                    PlayTimeDiff FLOAT(4,1),
                    SideofField VARCHAR(3),
                    yrdln FLOAT(3,1),
                    yrdline100 FLOAT(3,1),
                    ydstogo INT,
                    ydsnet INT,
                    GoalToGo FLOAT(2,1),
                    FirstDown FLOAT(2,1),
                    posteam VARCHAR(3),
                    DefensiveTeam VARCHAR(3),
                    description TEXT(572),
                    PlayAttempted INT,
                    YardsGained INT,
                    sp INT,
                    Touchdown INT,
                    ExPointResult ENUM('Made','Missed','Aborted'),
                    TwoPointConv ENUM('Failure','Success'),
                    DefTwoPoint ENUM('Failure','Success'),
                    Safety INT,
                    PuntResult ENUM('Clean','Blocked'),
                    PlayType VARCHAR(18),
                    Passer VARCHAR(16),
                    PassAttempt INT,
                    PassOutcome ENUM('Complete','Incomplete Pass'),
                    PassLength ENUM('Short','Deep'),
                    PassLocation ENUM('left','middle','right'),
                    InterceptionThrown INT,
                    Interceptor VARCHAR(19),
                    Rusher VARCHAR(16),
                    RushAttempt INT,
                    RunLocation ENUM('left','middle','right'),
                    RunGap ENUM('end','guard','tackle'),
                    Receiver VARCHAR(14),
                    Reception INT,
                    ReturnResult ENUM('Touchback','Fair Catch','Touchdown'),
                    Returner VARCHAR(14),
                    BlockingPlayer VARCHAR(11),
                    Tackler1 VARCHAR(19),
                    Tackler2 VARCHAR(15),
                    FieldGoalResult ENUM('Good','No Good','Blocked'),
                    FieldGoalDistance FLOAT(3,1),
                    Fumble INT,
                    RecFumbTeam VARCHAR(3),
                    RecFumbPlayer VARCHAR(19),
                    Sack INT,
                    ChallengeReplay INT,
                    ChalReplayResult ENUM('Upheld','Reversed'),
                    AcceptedPenalty INT,
                    PenalizedTeam VARCHAR(3),
                    PenaltyType VARCHAR(235),
                    PenalizedPlayer VARCHAR(19),
                    PenaltyYards INT,
                    PosTeamScore FLOAT(3,1),
                    DefTeamScore FLOAT(3,1),
                    ScoreDiff FLOAT(3,1),
                    AbsScoreDiff FLOAT(3,1),
                    Season CHAR(4));
LOAD DATA LOCAL INFILE '/path/to/csv' INTO TABLE plays
FIELDS TERMINATED BY ',' ENCLOSED BY '"' IGNORE 1 LINES;
